name: Run Unit Tests on Push

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Pods
      run: pod install
    - name: Build
      run: swift build -v
    - name: Run Unit Tests
      run: swift test -v
